name: Pull Docker Images

on:
  workflow_dispatch:

jobs:
  pull-images:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up Docker
      #   uses: docker/setup-buildx-action@v3

      # - uses: ./.github/actions/docker-login
      #   with:
      #     username: tedim52
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - uses: ./.github/actions/docker-login
      #   with:
      #     username: ethpandaops
      #     password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Pull Docker Hub Images
        run: |
          images=(
            "alpine"
            "ubuntu"
            "nginx"
            "redis"
            "postgres"
            "node"
            "python"
            "golang"
            "mongo"
            "mysql"
            "busybox"
            "httpd"
            "debian"
            "traefik"
            "elasticsearch"
            "logstash"
            "kibana"
            "vault"
            "consul"
            "haproxy"
            "php"
            "ruby"
            "openjdk"
            "tomcat"
            "influxdb"
            "grafana/grafana"
            "prom/prometheus"
            "prom/alertmanager"
            "telegraf"
            "zookeeper"
            "cassandra"
            "rabbitmq"
            "bitnami/nginx"
            "bitnami/mariadb"
            "bitnami/redis"
            "bitnami/postgresql"
            "bitnami/mongodb"
            "bitnami/jenkins"
            "bitnami/grafana"
            "bitnami/prometheus"
            "bitnami/apache"
            "bitnami/minio"
            "bitnami/kafka"
            "bitnami/zookeeper"
            "bitnami/wordpress"
            "bitnami/drupal"
            "bitnami/magento"
            "portainer/portainer-ce"
            "linuxserver/plex"
            "linuxserver/jellyfin"
            "linuxserver/swag"
            "linuxserver/qbittorrent"
            "linuxserver/sonarr"
            "linuxserver/radarr"
            "linuxserver/lidarr"
            "docker:dind"
            "docker:latest"
            "docker/compose"
            "hello-world"
            "hashicorp/terraform"
            "hashicorp/vault"
            "hashicorp/consul"
            "circleci/node"
            "circleci/python"
            "circleci/golang"
            "circleci/openjdk"
            "circleci/ruby"
            "circleci/php"
            "circleci/mysql"
            "circleci/postgres"
            "circleci/mongo"
            "circleci/redis"
            "circleci/nginx"
            "circleci/docker"
            "amazonlinux"
            "rockylinux/rockylinux"
            "fedora"
            "archlinux"
            "clearlinux/stable"
            "oraclelinux"
            "centos"
            "opensuse/leap"
            "opensuse/tumbleweed"
            "tensorflow/tensorflow"
            "pytorch/pytorch"
            "jupyter/scipy-notebook"
            "jupyter/base-notebook"
            "jupyter/minimal-notebook"
            "apache/airflow"
            "confluentinc/cp-kafka"
            "confluentinc/cp-zookeeper"
            "confluentinc/cp-schema-registry"
            "confluentinc/cp-kafka-connect"
            "minio/minio"
            "selenium/standalone-chrome"
            "selenium/standalone-firefox"
          )

          for image in "${images[@]}"; do
            echo "Pulling $image..."
            docker pull "docker.io/$image" || echo "Failed to pull $image — skipping."
          done